name: Run tests

on:
  pull_request:
    branches:
      - master

jobs:
  test38:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build package
        uses: abatilo/actions-poetry@v1.11.0
        with:
          python_version: 3.8
          args: run pytest tests/

  test27:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build package
        uses: abatilo/actions-poetry@v1.11.0
        with:
          python_version: 2.7
          args: run pytest tests/
